<Project Sdk="Microsoft.NET.Sdk">
    <PropertyGroup>
        <TargetFramework>net10.0</TargetFramework>
        <LangVersion>latest</LangVersion>
        <IsPackable>false</IsPackable>
        <CopyLocalLockFileAssemblies>true</CopyLocalLockFileAssemblies>
        <IsTestProject>true</IsTestProject>
    </PropertyGroup>

    <ItemGroup>
        <PackageReference Include="coverlet.collector" Version="6.0.4" />
        <PackageReference Include="Microsoft.NET.Test.Sdk" Version="17.14.0" />
        <PackageReference Include="NSubstitute" Version="5.3.0" />
        <PackageReference Include="NUnit" Version="4.3.2" />
        <PackageReference Include="NUnit.Analyzers" Version="4.7.0" />
        <PackageReference Include="NUnit3TestAdapter" Version="5.0.0" />
    </ItemGroup>

    <ItemGroup>
        <Reference Include="VintagestoryAPI">
            <HintPath>$(VINTAGE_STORY)/VintagestoryAPI.dll</HintPath>
            <Private>true</Private>
        </Reference>
        <Reference Include="VSSurvivalMod">
            <HintPath>$(VINTAGE_STORY)/Mods/VSSurvivalMod.dll</HintPath>
            <Private>true</Private>
        </Reference>
        <Reference Include="VSEssentials">
            <HintPath>$(VINTAGE_STORY)/Mods/VSEssentials.dll</HintPath>
            <Private>true</Private>
        </Reference>
        <Reference Include="VSCreativeMod">
            <HintPath>$(VINTAGE_STORY)/Mods/VSCreativeMod.dll</HintPath>
            <Private>true</Private>
        </Reference>
        <Reference Include="Harmony">
            <HintPath>$(VINTAGE_STORY)/Lib/0Harmony.dll</HintPath>
            <Private>true</Private>
        </Reference>
        <Reference Include="protobuf-net">
            <HintPath>$(VINTAGE_STORY)\Lib\protobuf-net.dll</HintPath>
            <Private>true</Private>
        </Reference>
        <Reference Include="Microsoft.Data.Sqlite">
            <HintPath>$(VINTAGE_STORY)\Lib\Microsoft.Data.Sqlite.dll</HintPath>
            <Private>true</Private>
        </Reference>
        <Reference Include="SQLitePCLRaw.batteries_v2">
            <HintPath>$(VINTAGE_STORY)\Lib\SQLitePCLRaw.batteries_v2.dll</HintPath>
            <Private>true</Private>
        </Reference>
        <Reference Include="SQLitePCLRaw.provider.e_sqlite3">
            <HintPath>$(VINTAGE_STORY)\Lib\SQLitePCLRaw.provider.e_sqlite3.dll</HintPath>
            <Private>true</Private>
        </Reference>
    </ItemGroup>

    <ItemGroup>
        <None Include="$(VINTAGE_STORY)\Lib\e_sqlite3.dll" Link="e_sqlite3.dll" CopyToOutputDirectory="PreserveNewest" Condition="Exists('$(VINTAGE_STORY)\Lib\e_sqlite3.dll')" />
        <None Include="$(VINTAGE_STORY)\Lib\libe_sqlite3.so" Link="libe_sqlite3.so" CopyToOutputDirectory="PreserveNewest" Condition="Exists('$(VINTAGE_STORY)\Lib\libe_sqlite3.so')" />
        <None Include="$(VINTAGE_STORY)\Lib\libe_sqlite3.dylib" Link="libe_sqlite3.dylib" CopyToOutputDirectory="PreserveNewest" Condition="Exists('$(VINTAGE_STORY)\Lib\libe_sqlite3.dylib')" />
        <Using Include="NUnit.Framework" />
    </ItemGroup>

    <ItemGroup>
        <ProjectReference Include="..\KsCartographyTable\KsCartographyTable.csproj" />
        <PackageReference Include="SQLitePCLRaw.bundle_e_sqlite3" Version="2.1.11" />
    </ItemGroup>

</Project>
